server:
  port: 9201
spring:
  profiles:
    active: dev
  application:
    name: platform-gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: @pom.nacos.ip@:@pom.nacos.port@
        namespace: @pom.nacos.namespace@
    gateway:
      routes: #配置路由规则
        - id: domain-user-service
          uri: lb://domain-user-service
          predicates:
            - Path=/mall-admin/**
          filters:
            - StripPrefix=1
        - id: platform-authority-service
          uri: lb://platform-authority-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9401/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    host: @redis.host@ # Redis服务器地址
    database: @redis.database@ # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: @redis.password@ # Redis服务器连接密码（默认为空）
#    timeout: 3000ms # 连接超时时间（毫秒）
secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/auth/oauth/**"
      - "/mall-admin/admin/login"
      - "/mall-admin/admin/register"
      - "/mall-admin/minio/upload"

