server:
  port: 9401
spring:
  application:
    name: platform-authority-service
  cloud:
    nacos:
      discovery:
        server-addr: @pom.nacos.ip@:@pom.nacos.port@
        namespace: @pom.nacos.namespace@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: @redis.host@ # Redis服务器地址
    database: @redis.database@ # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: @redis.password@ # Redis服务器连接密码（默认为空）
#    timeout: 3000ms # 连接超时时间（毫秒）
management:
  endpoints:
    web:
      exposure:
        include: "*"